/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bmspackage;

/**
 *
 * @author MAA COMPUTERS
 */
public class AddCustomerForm extends javax.swing.JFrame {

    /**
     * Creates new form AddCustomerForm
     */
    public AddCustomerForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        customerIDtxtfield = new javax.swing.JTextField();
        customerID = new javax.swing.JLabel();
        customerPNOtxtfield = new javax.swing.JTextField();
        customerPhoneNumber = new javax.swing.JLabel();
        customerCitytxtfield = new javax.swing.JTextField();
        customerCity = new javax.swing.JLabel();
        customerZipCode = new javax.swing.JLabel();
        customerZipCodetxtfield = new javax.swing.JTextField();
        customerProvince = new javax.swing.JLabel();
        customerProvincetxtfield = new javax.swing.JTextField();
        customerAddresstxtfield = new javax.swing.JTextField();
        customerAddress = new javax.swing.JLabel();
        customerEmailtxtfield = new javax.swing.JTextField();
        customerEmail = new javax.swing.JLabel();
        customerINametxtfield = new javax.swing.JTextField();
        CustomerName = new javax.swing.JLabel();
        AddButton = new javax.swing.JButton();
        AddCustomerForm = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        RemoveCustomer = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bloom's Boutique");

        jPanel1.setBackground(new java.awt.Color(225, 204, 183));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(196,164,132,80));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        customerIDtxtfield.setBackground(new java.awt.Color(196, 164, 132));
        customerIDtxtfield.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(customerIDtxtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 132, -1));

        customerID.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        customerID.setForeground(new java.awt.Color(255, 255, 255));
        customerID.setText("Customer ID:");
        jPanel2.add(customerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        customerPNOtxtfield.setBackground(new java.awt.Color(196, 164, 132));
        customerPNOtxtfield.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(customerPNOtxtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 132, -1));

        customerPhoneNumber.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        customerPhoneNumber.setForeground(new java.awt.Color(255, 255, 255));
        customerPhoneNumber.setText("Phone Number:");
        jPanel2.add(customerPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        customerCitytxtfield.setBackground(new java.awt.Color(196, 164, 132));
        customerCitytxtfield.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(customerCitytxtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 132, -1));

        customerCity.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        customerCity.setForeground(new java.awt.Color(255, 255, 255));
        customerCity.setText("City:");
        jPanel2.add(customerCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 41, -1));

        customerZipCode.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        customerZipCode.setForeground(new java.awt.Color(255, 255, 255));
        customerZipCode.setText("Zip Code:");
        jPanel2.add(customerZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 90, -1));

        customerZipCodetxtfield.setBackground(new java.awt.Color(196, 164, 132));
        customerZipCodetxtfield.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(customerZipCodetxtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 132, -1));

        customerProvince.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        customerProvince.setForeground(new java.awt.Color(255, 255, 255));
        customerProvince.setText("Province:");
        jPanel2.add(customerProvince, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, 100, -1));

        customerProvincetxtfield.setBackground(new java.awt.Color(196, 164, 132));
        customerProvincetxtfield.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(customerProvincetxtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, 170, -1));

        customerAddresstxtfield.setBackground(new java.awt.Color(196, 164, 132));
        customerAddresstxtfield.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(customerAddresstxtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 170, -1));

        customerAddress.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        customerAddress.setForeground(new java.awt.Color(255, 255, 255));
        customerAddress.setText("Address:");
        jPanel2.add(customerAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 80, -1));

        customerEmailtxtfield.setBackground(new java.awt.Color(196, 164, 132));
        customerEmailtxtfield.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(customerEmailtxtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 170, -1));

        customerEmail.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        customerEmail.setForeground(new java.awt.Color(255, 255, 255));
        customerEmail.setText("Email:");
        jPanel2.add(customerEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 60, -1));

        customerINametxtfield.setBackground(new java.awt.Color(196, 164, 132));
        customerINametxtfield.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(customerINametxtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 160, -1));

        CustomerName.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        CustomerName.setForeground(new java.awt.Color(255, 255, 255));
        CustomerName.setText("Name:");
        jPanel2.add(CustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 65, -1));

        AddButton.setBackground(new java.awt.Color(196, 164, 132));
        AddButton.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        AddButton.setForeground(new java.awt.Color(255, 255, 255));
        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });
        jPanel2.add(AddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, 83, -1));

        AddCustomerForm.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        AddCustomerForm.setForeground(new java.awt.Color(255, 255, 255));
        AddCustomerForm.setText("Add Customer");
        jPanel2.add(AddCustomerForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 324, -1));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bmspackage/WhatsApp Image 2024-06-10 at 1.01.30 AM.jpeg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 730, 450));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Add a new customer by entering the data below:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 880, 570));

        jMenu2.setText("Edit");

        RemoveCustomer.setText("Back to Customer");
        RemoveCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveCustomerActionPerformed(evt);
            }
        });
        jMenu2.add(RemoveCustomer);

        jMenuItem2.setText("Dashboard");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
    // Retrieve data from text fields
//    int id = Integer.parseInt(customerIDtxtfield.getText());
//    String name = customerINametxtfield.getText();
//    String email = customerEmailtxtfield.getText();
//    String phoneNumber = customerPNOtxtfield.getText();
//    String address = customerAddresstxtfield.getText();
//    String city = customerCitytxtfield.getText();
//    String province = customerProvincetxtfield.getText();
//    String zipCode = customerZipCodetxtfield.getText();
//
//    // Create a new Customer object and add the customer
//    Customer customer = new Customer(id, name, phoneNumber, address, "", phoneNumber, email, city, province, zipCode);
//        
////    Customer customer = new Customer(id, name,  email,phoneNumber, address, city, province, zipCode);
//  customer.add(id, name, email, phoneNumber, address, city, province, zipCode);
 int id = Integer.parseInt(customerIDtxtfield.getText());
    String name = customerINametxtfield.getText();
    String email = customerEmailtxtfield.getText();
    String phoneNumber = customerPNOtxtfield.getText();
    String address = customerAddresstxtfield.getText();
    String city = customerCitytxtfield.getText();
    String province = customerProvincetxtfield.getText();
    String zipCode = customerZipCodetxtfield.getText();

    // Create a new Customer object and add the customer
    Customer customer = new Customer(id, name, phoneNumber, email, address, city, province, zipCode);
    customer.add(id, name, email, phoneNumber, address, city, province, zipCode);

    }//GEN-LAST:event_AddButtonActionPerformed

    private void RemoveCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveCustomerActionPerformed
CustomerForm form=new CustomerForm();
        form.setVisible(true);    }//GEN-LAST:event_RemoveCustomerActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
         Dashboard db = new Dashboard();
        db.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCustomerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JLabel AddCustomerForm;
    private javax.swing.JLabel CustomerName;
    private javax.swing.JMenuItem RemoveCustomer;
    private javax.swing.JLabel customerAddress;
    private javax.swing.JTextField customerAddresstxtfield;
    private javax.swing.JLabel customerCity;
    private javax.swing.JTextField customerCitytxtfield;
    private javax.swing.JLabel customerEmail;
    private javax.swing.JTextField customerEmailtxtfield;
    private javax.swing.JLabel customerID;
    private javax.swing.JTextField customerIDtxtfield;
    private javax.swing.JTextField customerINametxtfield;
    private javax.swing.JTextField customerPNOtxtfield;
    private javax.swing.JLabel customerPhoneNumber;
    private javax.swing.JLabel customerProvince;
    private javax.swing.JTextField customerProvincetxtfield;
    private javax.swing.JLabel customerZipCode;
    private javax.swing.JTextField customerZipCodetxtfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
