/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bmspackage;
import java.text.SimpleDateFormat;
import java.util.Date;
/**
 *
 * @author MAA COMPUTERS
 */
public class AddStaffForm extends javax.swing.JFrame {

    /**
     * Creates new form AddCustomerForm
     */
    public AddStaffForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        staffIDtxtfield = new javax.swing.JTextField();
        staffID = new javax.swing.JLabel();
        AddStaffForm = new javax.swing.JLabel();
        staffContactInformation = new javax.swing.JLabel();
        staffContactInformationtxtfield = new javax.swing.JTextField();
        staffPositiontxtfield = new javax.swing.JTextField();
        staffPosition = new javax.swing.JLabel();
        staffNametxtfield = new javax.swing.JTextField();
        staffName = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        staffDOB = new javax.swing.JLabel();
        customerAddress = new javax.swing.JLabel();
        staffAddresstxtfield = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        Back = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bloom's Boutique");

        jPanel1.setBackground(new java.awt.Color(225, 204, 183));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(196,164,132,80));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        staffIDtxtfield.setBackground(new java.awt.Color(196, 164, 132));
        staffIDtxtfield.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(staffIDtxtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 100, -1));

        staffID.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        staffID.setForeground(new java.awt.Color(255, 255, 255));
        staffID.setText("Staff member ID:");
        jPanel2.add(staffID, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 150, -1));

        AddStaffForm.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        AddStaffForm.setForeground(new java.awt.Color(255, 255, 255));
        AddStaffForm.setText("STAFF");
        jPanel2.add(AddStaffForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 120, 70));

        staffContactInformation.setFont(new java.awt.Font("Trebuchet MS", 1, 17)); // NOI18N
        staffContactInformation.setForeground(new java.awt.Color(255, 255, 255));
        staffContactInformation.setText("Contact Information:");
        jPanel2.add(staffContactInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 180, -1));

        staffContactInformationtxtfield.setBackground(new java.awt.Color(196, 164, 132));
        staffContactInformationtxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffContactInformationtxtfieldActionPerformed(evt);
            }
        });
        jPanel2.add(staffContactInformationtxtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 110, -1));

        staffPositiontxtfield.setBackground(new java.awt.Color(196, 164, 132));
        jPanel2.add(staffPositiontxtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 120, -1));

        staffPosition.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        staffPosition.setForeground(new java.awt.Color(255, 255, 255));
        staffPosition.setText("Position:");
        jPanel2.add(staffPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 100, -1));

        staffNametxtfield.setBackground(new java.awt.Color(196, 164, 132));
        staffNametxtfield.setForeground(new java.awt.Color(255, 255, 255));
        staffNametxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffNametxtfieldActionPerformed(evt);
            }
        });
        jPanel2.add(staffNametxtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 100, -1));

        staffName.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        staffName.setForeground(new java.awt.Color(255, 255, 255));
        staffName.setText("Name :");
        jPanel2.add(staffName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 65, -1));

        jDateChooser1.setBackground(new java.awt.Color(196, 164, 132));
        jDateChooser1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, -1, -1));

        staffDOB.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        staffDOB.setForeground(new java.awt.Color(255, 255, 255));
        staffDOB.setText("Date Of Birth:");
        jPanel2.add(staffDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, -1, -1));

        customerAddress.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        customerAddress.setForeground(new java.awt.Color(255, 255, 255));
        customerAddress.setText("Address:");
        jPanel2.add(customerAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 90, -1));

        staffAddresstxtfield.setBackground(new java.awt.Color(196, 164, 132));
        staffAddresstxtfield.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(staffAddresstxtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, 120, 30));

        AddButton.setBackground(new java.awt.Color(196, 164, 132));
        AddButton.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        AddButton.setForeground(new java.awt.Color(255, 255, 255));
        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });
        jPanel2.add(AddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, 83, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bmspackage/bms_staff.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 570, 400));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Add staff member by entering the data below:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 400, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 710, 570));

        jMenu2.setText("Edit");

        Back.setText("Back to Staff");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jMenu2.add(Back);

        jMenuItem2.setText("Dashboard");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
   int staffID = Integer.parseInt(staffIDtxtfield.getText());
    String staffName = staffNametxtfield.getText();
    String staffPosition = staffPositiontxtfield.getText();
    String staffContactInformation = staffContactInformationtxtfield.getText();
    String staffAddress = staffAddresstxtfield.getText();
    
    // Ensure the JDateChooser date format is set
    jDateChooser1.setDateFormatString("yyyy-MM-dd");
    
    // Get the date from JDateChooser and format it
    Date dateOfBirth = jDateChooser1.getDate();
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    String staffDateOfBirth = dateFormat.format(dateOfBirth);

    // Create a new Staff object using the constructor
    Staff staff = new Staff(staffID, staffName, staffContactInformation, staffAddress, staffDateOfBirth, staffPosition);
    
    // Add the staff member with the new fields
    staff.add(staffID, staffName, staffPosition, staffContactInformation, staffAddress, staffDateOfBirth, null, null);

    }//GEN-LAST:event_AddButtonActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        StaffForm form=new StaffForm();
        form.setVisible(true);        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_BackActionPerformed

    private void staffContactInformationtxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffContactInformationtxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staffContactInformationtxtfieldActionPerformed

    private void staffNametxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffNametxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staffNametxtfieldActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
         Dashboard db = new Dashboard();
        db.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStaffForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStaffForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStaffForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStaffForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddStaffForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JLabel AddStaffForm;
    private javax.swing.JMenuItem Back;
    private javax.swing.JLabel customerAddress;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField staffAddresstxtfield;
    private javax.swing.JLabel staffContactInformation;
    private javax.swing.JTextField staffContactInformationtxtfield;
    private javax.swing.JLabel staffDOB;
    private javax.swing.JLabel staffID;
    private javax.swing.JTextField staffIDtxtfield;
    private javax.swing.JLabel staffName;
    private javax.swing.JTextField staffNametxtfield;
    private javax.swing.JLabel staffPosition;
    private javax.swing.JTextField staffPositiontxtfield;
    // End of variables declaration//GEN-END:variables
}
