/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bmspackage;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author DANISH LAPTOP
 */
public class OrderUpdateForm extends javax.swing.JFrame {

    /**
     * Creates new form InventoryForm
     */
    public OrderUpdateForm() {
        initComponents();
        customerComboBox.removeAllItems();
        staffComboBox.removeAllItems();
        populateCustomerComboBox();
        populateStaffComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem7 = new javax.swing.JMenuItem();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtOrdId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        customerComboBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtOrdAmount = new javax.swing.JTextField();
        statusComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        staffComboBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        paymentComboBox = new javax.swing.JComboBox<>();
        btnUpdate = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenuItem7.setText("jMenuItem7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bloom's Boutique");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 72, 326, -1));

        jPanel1.setBackground(new java.awt.Color(225, 204, 183));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(93,71,58,80));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ORDER");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 140, -1));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Order ID:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 90, -1));

        txtOrdId.setBackground(new java.awt.Color(150, 121, 105));
        txtOrdId.setForeground(new java.awt.Color(255, 255, 255));
        txtOrdId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrdIdActionPerformed(evt);
            }
        });
        jPanel2.add(txtOrdId, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 120, -1));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Customer: ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 100, -1));

        customerComboBox.setBackground(new java.awt.Color(150, 121, 105));
        customerComboBox.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        customerComboBox.setForeground(new java.awt.Color(255, 255, 255));
        customerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        customerComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerComboBoxActionPerformed(evt);
            }
        });
        jPanel2.add(customerComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 110, -1));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Total Amount:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, -1, -1));

        txtOrdAmount.setBackground(new java.awt.Color(150, 121, 105));
        txtOrdAmount.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jPanel2.add(txtOrdAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, 110, -1));

        statusComboBox.setBackground(new java.awt.Color(150, 121, 105));
        statusComboBox.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        statusComboBox.setForeground(new java.awt.Color(255, 255, 255));
        statusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Processing", "Shipped", "Out for delivery", "Delivered", "Cancelled", " " }));
        statusComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusComboBoxActionPerformed(evt);
            }
        });
        jPanel2.add(statusComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Order Status:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, -1, 24));

        staffComboBox.setBackground(new java.awt.Color(150, 121, 105));
        staffComboBox.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        staffComboBox.setForeground(new java.awt.Color(255, 255, 255));
        staffComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(staffComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 110, -1));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Staff:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 52, -1));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Order Date:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 110, -1));

        jDateChooser1.setBackground(new java.awt.Color(150, 121, 105));
        jDateChooser1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 110, -1));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Payment Method:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 150, -1));

        paymentComboBox.setBackground(new java.awt.Color(150, 121, 105));
        paymentComboBox.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        paymentComboBox.setForeground(new java.awt.Color(255, 255, 255));
        paymentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Credit card", "Debit card", "Bank Transfer", "Cash on delivery" }));
        jPanel2.add(paymentComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 110, -1));

        btnUpdate.setBackground(new java.awt.Color(150, 121, 105));
        btnUpdate.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 140, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bmspackage/bms_order.jpg"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, 420));

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Update an existing order by entering Data below:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 700, 560));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 680));

        jMenu2.setText("Menu");

        jMenuItem8.setText("Back to Order");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuItem1.setText("Dashboard");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtOrdIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrdIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrdIdActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
 int Orderid= Integer.parseInt(txtOrdId.getText());
      Customer selectedCustomer = (Customer) customerComboBox.getSelectedItem();
      String orderStatus = (String) statusComboBox.getSelectedItem();
            int amount= Integer.parseInt(txtOrdAmount.getText());
            Staff selectedStaff = (Staff) staffComboBox.getSelectedItem();
            String paymentMethod = (String) paymentComboBox.getSelectedItem();
//      int Reorder= Integer.parseInt(txtReorder.getText());
        String Location= txtOrdAmount.getText();
        jDateChooser1.setDateFormatString("yyyy-MM-dd");
    
    // Get the date from JDateChooser and format it
    Date date = jDateChooser1.getDate();
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    String orderDate = dateFormat.format(date);
    Order order = new Order (Orderid,selectedCustomer, orderDate,orderStatus,amount,selectedStaff,paymentMethod);
       order.updateOrder();

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        OrderForm form = new OrderForm();
        form.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void customerComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerComboBoxActionPerformed

    private void statusComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusComboBoxActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
         Dashboard db = new Dashboard();
        db.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    
       private void populateCustomerComboBox() {
       List<Customer> customers; // Use the Inventory instance to get products
    Order order = new Order();
    customers=order.getCustomersFromDatabase();
    
    DefaultComboBoxModel<Customer> model = (DefaultComboBoxModel)customerComboBox.getModel();// Create a model for Product objects
    for (Customer customer : customers) {
        model.addElement(customer); // Add Product objects directly to the model
    }
    System.out.println("Populated combo box with customers.");
    }
            private void populateStaffComboBox() {
       List<Staff> staffs; // Use the Inventory instance to get products
    Order order = new Order();
    staffs=order.getStaffFromDatabase();
    
    DefaultComboBoxModel<Staff> model = (DefaultComboBoxModel)staffComboBox.getModel();// Create a model for Product objects
    for (Staff staff : staffs) {
        model.addElement(staff); // Add Product objects directly to the model
    }
      System.out.println("Populated combo box with Staff.");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderUpdateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderUpdateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderUpdateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderUpdateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderUpdateForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> customerComboBox;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> paymentComboBox;
    private javax.swing.JComboBox<String> staffComboBox;
    private javax.swing.JComboBox<String> statusComboBox;
    private javax.swing.JTextField txtOrdAmount;
    private javax.swing.JTextField txtOrdId;
    // End of variables declaration//GEN-END:variables
}
