/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bmspackage;

/**
 *
 * @author MAA COMPUTERS
 */
public class UpdateStaffForm extends javax.swing.JFrame {

    /**
     * Creates new form AddCustomerForm
     */
    public UpdateStaffForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        UpdateStaffForm = new javax.swing.JLabel();
        staffIDtxtfield = new javax.swing.JTextField();
        staffID = new javax.swing.JLabel();
        staffContactInformation = new javax.swing.JLabel();
        staffContactInformationtxtfield = new javax.swing.JTextField();
        staffDOB = new javax.swing.JLabel();
        staffDOBtxtfield = new javax.swing.JTextField();
        staffName = new javax.swing.JLabel();
        staffPosition = new javax.swing.JLabel();
        customerAddress = new javax.swing.JLabel();
        staffAddresstxtfield = new javax.swing.JTextField();
        staffPositiontxtfield = new javax.swing.JTextField();
        staffNametxtfield = new javax.swing.JTextField();
        UpdateButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        Back = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bloom's Boutique");

        jPanel1.setBackground(new java.awt.Color(225, 204, 183));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(196,164,132,80));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UpdateStaffForm.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        UpdateStaffForm.setForeground(new java.awt.Color(255, 255, 255));
        UpdateStaffForm.setText("STAFF");
        jPanel2.add(UpdateStaffForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 140, -1));

        staffIDtxtfield.setBackground(new java.awt.Color(196, 164, 132));
        staffIDtxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffIDtxtfieldActionPerformed(evt);
            }
        });
        jPanel2.add(staffIDtxtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 114, -1));

        staffID.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        staffID.setForeground(new java.awt.Color(255, 255, 255));
        staffID.setText("Staff ID:");
        jPanel2.add(staffID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 70, -1));

        staffContactInformation.setFont(new java.awt.Font("Trebuchet MS", 1, 17)); // NOI18N
        staffContactInformation.setForeground(new java.awt.Color(255, 255, 255));
        staffContactInformation.setText("Contact Information:");
        jPanel2.add(staffContactInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        staffContactInformationtxtfield.setBackground(new java.awt.Color(196, 164, 132));
        staffContactInformationtxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffContactInformationtxtfieldActionPerformed(evt);
            }
        });
        jPanel2.add(staffContactInformationtxtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 114, -1));

        staffDOB.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        staffDOB.setForeground(new java.awt.Color(255, 255, 255));
        staffDOB.setText("Date Of Birth:");
        jPanel2.add(staffDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, -1, -1));

        staffDOBtxtfield.setBackground(new java.awt.Color(196, 164, 132));
        staffDOBtxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffDOBtxtfieldActionPerformed(evt);
            }
        });
        jPanel2.add(staffDOBtxtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 114, -1));

        staffName.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        staffName.setForeground(new java.awt.Color(255, 255, 255));
        staffName.setText("Name:");
        jPanel2.add(staffName, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 65, -1));

        staffPosition.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        staffPosition.setForeground(new java.awt.Color(255, 255, 255));
        staffPosition.setText("Position:");
        jPanel2.add(staffPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 100, -1));

        customerAddress.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        customerAddress.setForeground(new java.awt.Color(255, 255, 255));
        customerAddress.setText("Address:");
        jPanel2.add(customerAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 90, -1));

        staffAddresstxtfield.setBackground(new java.awt.Color(196, 164, 132));
        staffAddresstxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffAddresstxtfieldActionPerformed(evt);
            }
        });
        jPanel2.add(staffAddresstxtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 330, 150, -1));

        staffPositiontxtfield.setBackground(new java.awt.Color(196, 164, 132));
        staffPositiontxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffPositiontxtfieldActionPerformed(evt);
            }
        });
        jPanel2.add(staffPositiontxtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 240, 160, -1));

        staffNametxtfield.setBackground(new java.awt.Color(196, 164, 132));
        staffNametxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffNametxtfieldActionPerformed(evt);
            }
        });
        jPanel2.add(staffNametxtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 160, 150, -1));

        UpdateButton.setBackground(new java.awt.Color(196, 164, 132));
        UpdateButton.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        UpdateButton.setForeground(new java.awt.Color(255, 255, 255));
        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });
        jPanel2.add(UpdateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 120, -1));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Update staff member information by inserting the data below:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 530, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bmspackage/bms_staff.jpg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 580, 380));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 730, 540));

        jMenu2.setText("Back");

        Back.setText("Back to Staff");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jMenu2.add(Back);

        jMenuItem1.setText("Dashboard");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
    // Retrieve data from text fields
    int staffID = Integer.parseInt(staffIDtxtfield.getText());
    String staffName = staffNametxtfield.getText();
    String staffPosition = staffPositiontxtfield.getText();
    String staffContactInformation = staffContactInformationtxtfield.getText();
    String staffAddress = staffAddresstxtfield.getText();
    String staffDateOfBirth = staffDOBtxtfield.getText();

    // Create a new Staff object using the constructor
    Staff staff = new Staff(staffID, staffName, staffContactInformation, staffAddress, staffDateOfBirth, staffPosition);

    // Update the staff details
    staff.updateDetails();

    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void staffDOBtxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffDOBtxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staffDOBtxtfieldActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        StaffForm form=new StaffForm();
        form.setVisible(true);        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_BackActionPerformed

    private void staffIDtxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffIDtxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staffIDtxtfieldActionPerformed

    private void staffNametxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffNametxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staffNametxtfieldActionPerformed

    private void staffAddresstxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffAddresstxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staffAddresstxtfieldActionPerformed

    private void staffContactInformationtxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffContactInformationtxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staffContactInformationtxtfieldActionPerformed

    private void staffPositiontxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffPositiontxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staffPositiontxtfieldActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
         Dashboard db = new Dashboard();
        db.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateStaffForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateStaffForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateStaffForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateStaffForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateStaffForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Back;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JLabel UpdateStaffForm;
    private javax.swing.JLabel customerAddress;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField staffAddresstxtfield;
    private javax.swing.JLabel staffContactInformation;
    private javax.swing.JTextField staffContactInformationtxtfield;
    private javax.swing.JLabel staffDOB;
    private javax.swing.JTextField staffDOBtxtfield;
    private javax.swing.JLabel staffID;
    private javax.swing.JTextField staffIDtxtfield;
    private javax.swing.JLabel staffName;
    private javax.swing.JTextField staffNametxtfield;
    private javax.swing.JLabel staffPosition;
    private javax.swing.JTextField staffPositiontxtfield;
    // End of variables declaration//GEN-END:variables
}
