/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bmspackage;

/**
 *
 * @author MAA COMPUTERS
 */
public class UpdateCustomerForm extends javax.swing.JFrame {

    /**
     * Creates new form AddCustomerForm
     */
    public UpdateCustomerForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        customerAddress = new javax.swing.JLabel();
        customerProvince = new javax.swing.JLabel();
        customerProvincetxtfield = new javax.swing.JTextField();
        customerAddresstxtfield = new javax.swing.JTextField();
        customerEmail = new javax.swing.JLabel();
        customerEmailtxtfield = new javax.swing.JTextField();
        customerINametxtfield = new javax.swing.JTextField();
        CustomerName = new javax.swing.JLabel();
        UpdateButton = new javax.swing.JButton();
        customerZipCodetxtfield = new javax.swing.JTextField();
        customerCitytxtfield = new javax.swing.JTextField();
        customerPNOtxtfield = new javax.swing.JTextField();
        customerIDtxtfield = new javax.swing.JTextField();
        customerID = new javax.swing.JLabel();
        customerPhoneNumber = new javax.swing.JLabel();
        customerCity = new javax.swing.JLabel();
        customerZipCode = new javax.swing.JLabel();
        AddCustomerForm = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        Back = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bloom's Boutique");

        jPanel1.setBackground(new java.awt.Color(225, 204, 183));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(196,164,132,80));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        customerAddress.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        customerAddress.setForeground(new java.awt.Color(255, 255, 255));
        customerAddress.setText("Address:");
        jPanel2.add(customerAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 90, -1));

        customerProvince.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        customerProvince.setForeground(new java.awt.Color(255, 255, 255));
        customerProvince.setText("Province:");
        jPanel2.add(customerProvince, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, 90, -1));

        customerProvincetxtfield.setBackground(new java.awt.Color(196, 164, 132));
        customerProvincetxtfield.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        customerProvincetxtfield.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(customerProvincetxtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, 130, -1));

        customerAddresstxtfield.setBackground(new java.awt.Color(196, 164, 132));
        customerAddresstxtfield.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        customerAddresstxtfield.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(customerAddresstxtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 130, -1));

        customerEmail.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        customerEmail.setForeground(new java.awt.Color(255, 255, 255));
        customerEmail.setText("Email:");
        jPanel2.add(customerEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 60, -1));

        customerEmailtxtfield.setBackground(new java.awt.Color(196, 164, 132));
        customerEmailtxtfield.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        customerEmailtxtfield.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(customerEmailtxtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 130, -1));

        customerINametxtfield.setBackground(new java.awt.Color(196, 164, 132));
        customerINametxtfield.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        customerINametxtfield.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(customerINametxtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 130, -1));

        CustomerName.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        CustomerName.setForeground(new java.awt.Color(255, 255, 255));
        CustomerName.setText("Name:");
        jPanel2.add(CustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 65, -1));

        UpdateButton.setBackground(new java.awt.Color(196, 164, 132));
        UpdateButton.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        UpdateButton.setForeground(new java.awt.Color(255, 255, 255));
        UpdateButton.setText("UPDATE");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });
        jPanel2.add(UpdateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, 150, -1));

        customerZipCodetxtfield.setBackground(new java.awt.Color(196, 164, 132));
        customerZipCodetxtfield.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        customerZipCodetxtfield.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(customerZipCodetxtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 132, -1));

        customerCitytxtfield.setBackground(new java.awt.Color(196, 164, 132));
        customerCitytxtfield.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        customerCitytxtfield.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(customerCitytxtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 132, -1));

        customerPNOtxtfield.setBackground(new java.awt.Color(196, 164, 132));
        customerPNOtxtfield.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        customerPNOtxtfield.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(customerPNOtxtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 132, -1));

        customerIDtxtfield.setBackground(new java.awt.Color(196, 164, 132));
        customerIDtxtfield.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(customerIDtxtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 132, -1));

        customerID.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        customerID.setForeground(new java.awt.Color(255, 255, 255));
        customerID.setText("ID:");
        jPanel2.add(customerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 41, -1));

        customerPhoneNumber.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        customerPhoneNumber.setForeground(new java.awt.Color(255, 255, 255));
        customerPhoneNumber.setText("Phone Number:");
        jPanel2.add(customerPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        customerCity.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        customerCity.setForeground(new java.awt.Color(255, 255, 255));
        customerCity.setText("City:");
        jPanel2.add(customerCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 41, -1));

        customerZipCode.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        customerZipCode.setForeground(new java.awt.Color(255, 255, 255));
        customerZipCode.setText("Zip Code:");
        jPanel2.add(customerZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 90, -1));

        AddCustomerForm.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        AddCustomerForm.setForeground(new java.awt.Color(255, 255, 255));
        AddCustomerForm.setText("UPDATE CUSTOMER");
        jPanel2.add(AddCustomerForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 367, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bmspackage/WhatsApp Image 2024-06-10 at 1.01.30 AM.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 600, 410));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Update an exiting customer records by entering Data below:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 770, 560));

        jMenu2.setText("Back");

        Back.setText("Back to Customer");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jMenu2.add(Back);

        jMenuItem1.setText("Dashboard");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
             // Retrieve data from text fields
//        int id = Integer.parseInt(customerIDtxtfield.getText());
//        String name = customerINametxtfield.getText();
//        String email = customerEmailtxtfield.getText();
//        String phoneNumber = customerPNOtxtfield.getText();
//        String address = customerAddresstxtfield.getText();
//        String city = customerCitytxtfield.getText();
//        String province = customerProvincetxtfield.getText();
//        String zipCode = customerZipCodetxtfield.getText();
//
//        // Create a new Customer object and set its fields
//        Customer customer = new Customer(id, name, phoneNumber, address, "", phoneNumber, email, city, province, zipCode);
//        
//        // Update the customer details
//        customer.updateDetails();
int id = Integer.parseInt(customerIDtxtfield.getText());
    String name = customerINametxtfield.getText();
    String email = customerEmailtxtfield.getText();
    String phoneNumber = customerPNOtxtfield.getText();
    String address = customerAddresstxtfield.getText();
    String city = customerCitytxtfield.getText();
    String province = customerProvincetxtfield.getText();
    String zipCode = customerZipCodetxtfield.getText();

    // Create a new Customer object and set its fields
    Customer customer = new Customer(id, name, phoneNumber, phoneNumber, address, city, province, zipCode);
    
    // Update the customer details
    customer.updateDetails();
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
  CustomerForm form=new CustomerForm();
        form.setVisible(true);        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_BackActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
         Dashboard db = new Dashboard();
        db.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateCustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateCustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateCustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateCustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateCustomerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddCustomerForm;
    private javax.swing.JMenuItem Back;
    private javax.swing.JLabel CustomerName;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JLabel customerAddress;
    private javax.swing.JTextField customerAddresstxtfield;
    private javax.swing.JLabel customerCity;
    private javax.swing.JTextField customerCitytxtfield;
    private javax.swing.JLabel customerEmail;
    private javax.swing.JTextField customerEmailtxtfield;
    private javax.swing.JLabel customerID;
    private javax.swing.JTextField customerIDtxtfield;
    private javax.swing.JTextField customerINametxtfield;
    private javax.swing.JTextField customerPNOtxtfield;
    private javax.swing.JLabel customerPhoneNumber;
    private javax.swing.JLabel customerProvince;
    private javax.swing.JTextField customerProvincetxtfield;
    private javax.swing.JLabel customerZipCode;
    private javax.swing.JTextField customerZipCodetxtfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
